/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_ibillxia_hellojni_HelloCal */

#ifndef _Included_io_ibillxia_hellojni_HelloCal
#define _Included_io_ibillxia_hellojni_HelloCal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_ibillxia_hellojni_HelloCal
 * Method:    helloSay
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring Java_io_ibillxia_hellojni_HelloCal_helloSay
  (JNIEnv *, jobject);

/*
 * Class:     io_ibillxia_hellojni_HelloCal
 * Method:    helloAdd
 * Signature: (II)I
 */
JNIEXPORT jint Java_io_ibillxia_hellojni_HelloCal_helloAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_ibillxia_hellojni_HelloCal
 * Method:    helloSub
 * Signature: (II)I
 */
JNIEXPORT jint Java_io_ibillxia_hellojni_HelloCal_helloSub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_ibillxia_hellojni_HelloCal
 * Method:    helloMul
 * Signature: (II)I
 */
JNIEXPORT jint Java_io_ibillxia_hellojni_HelloCal_helloMul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_ibillxia_hellojni_HelloCal
 * Method:    helloDiv
 * Signature: (II)I
 */
JNIEXPORT jint Java_io_ibillxia_hellojni_HelloCal_helloDiv
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
